[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "neurodatasets"
description = "Download and interface with a curated collection of large-scale public neuroscience datasets"
readme = "README.md"
requires-python = ">=3.14"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    { name = "Raj Magesh Gauthaman", email = "neurodatasets@raj-magesh.org" },
]
keywords = [
    "neural datasets",
    "Natural Scenes Dataset (NSD)",
    "THINGS-data collection",
    "THINGS Ventral stream Spiking Dataset (TVSD)",
    "BOLD5000",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
urls = { repository = "https://codeberg.org/raj-magesh/neurodatasets" }
dependencies = [
    "loguru",
    "osfclient",
    "boto3",
    "numpy",
    "pint",
    "pandas",
    "scipy",
    "Pillow",
    "mat73",
    "tqdm",
    "nibabel",
    "nilearn",
    "fast-simplification",
    "mne",
    "torch",
    "xarray",
    "xdg-base-dirs",
]
version = "0.1.0"

[dependency-groups]
dev = ["ruff", "pytest", "sphinx"]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
